name: Typedoc - Generate Web Documentation

on:
    pull_request:

jobs:
    lint:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v1

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: yarn install and lint
              run: |
                  yarn install
                  yarn run generate-docs
              env:
                  CI: true

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@4.1.4
              with:
                branch: master
                folder: docs
